import { products, capacities, colors } from '../data/catalog.js';
import { phoneVisual } from './phone.js';
export const stepNames = ['الجهاز','السعة','اللون','معلوماتك','التأكيد'];
export const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderStep(state) {
  const {step, productId, capacity, colorId, customer, errors, busy, success} = state;
  const product = products.find(p => p.id === productId);
  const color = colors.find(c => c.id === colorId);
  if (success) return `<div class="success"><span class="success-check" aria-hidden="true">✓</span><p class="eyebrow">خطوة أقرب إلى جهازك الجديد</p><h3 tabindex="-1">تم استلام طلب الحجز بنجاح</h3><p>شكراً لك. سيتم التواصل معك لتأكيد تفاصيل الحجز المسبق.</p><div class="reservation-id"><small>رقم الحجز التجريبي</small><strong dir="ltr">${escapeHtml(success.id)}</strong></div><div class="success-summary" dir="ltr">${product.name}<br>${capacity} · ${color.name}</div><p class="success-demo">هذه نسخة تجريبية للعرض ولا يتم إرسال الحجز فعلياً أو التواصل معك.</p><button class="primary" data-action="reset">إجراء حجز جديد</button><button class="text-button" data-action="home">العودة للرئيسية</button></div>`;
  const titles = ['اختر جهازك','اختر سعة التخزين','اختر اللون','معلومات الحجز','راجع تفاصيل حجزك'];
  const descriptions = ['حدد الجهاز الذي ترغب بحجزه مسبقاً.','مساحة أكبر لكل ما تحب. اختر السعة المناسبة لك.','لون يعبّر عنك. اختر لمستك الخاصة.','أدخل معلوماتك لمتابعة وتأكيد الحجز.','تأكد أن كل شيء كما ترغب قبل تأكيد الطلب.'];
  let content = '';
  if (step === 0) content = `<div class="product-grid" role="group" aria-label="اختيار الجهاز">${products.map(p => `<button class="product-card ${p.id===productId?'selected':''}" data-product="${p.id}" aria-pressed="${p.id===productId}"><span class="selection-check" aria-hidden="true">${p.id===productId?'✓':'+'}</span>${phoneVisual(p)}<strong dir="ltr">${p.name}</strong><small>${p.subtitle}</small><span class="availability">متاح للحجز المسبق</span><span class="card-choice">${p.id===productId?'تم الاختيار':'اختيار الجهاز'}</span></button>`).join('')}</div>`;
  if (step === 1) content = `<div class="capacity-grid" role="group" aria-label="اختيار السعة">${capacities.map(c => `<button class="capacity-card ${c===capacity?'selected':''}" data-capacity="${c}" aria-pressed="${c===capacity}"><strong dir="ltr">${c}</strong><span>${c===capacity?'✓ تم الاختيار':'سعة التخزين'}</span></button>`).join('')}</div><p class="help-note">اختر مساحة تناسب صورك وتطبيقاتك وملفاتك.</p>`;
  if (step === 2) content = `<div class="color-preview">${phoneVisual(product,color)}<span>${color ? color.arabic : 'اختر اللون المفضل لديك'}</span></div><div class="color-grid" role="group" aria-label="اختيار اللون">${colors.map(c => `<button class="color-card ${c.id===colorId?'selected':''}" data-color="${c.id}" aria-pressed="${c.id===colorId}"><span class="swatch" style="--swatch:${c.hex}"></span><strong lang="en">${c.name}</strong><small>${c.arabic}</small>${c.id===colorId?'<span class="color-check" aria-hidden="true">✓</span>':''}</button>`).join('')}</div>`;
  if (step === 3) content = `<form id="customer-form" novalidate>${[
    {id:'name',label:'الاسم الثلاثي',type:'text',placeholder:'الاسم الأول، اسم الأب، اسم العائلة',autocomplete:'name'},
    {id:'phone',label:'رقم الهاتف',type:'tel',placeholder:'07XXXXXXXXX',autocomplete:'tel'},
    {id:'email',label:'البريد الإلكتروني',type:'email',placeholder:'example@email.com',autocomplete:'email'}
  ].map(f=>`<div class="field"><label for="${f.id}">${f.label} <span aria-hidden="true">*</span></label><input id="${f.id}" name="${f.id}" type="${f.type}" autocomplete="${f.autocomplete}" ${f.id!=='name'?'dir="ltr"':''} maxlength="${f.id==='name'?120:f.id==='phone'?24:254}" placeholder="${f.placeholder}" value="${escapeHtml(customer[f.id])}" required aria-invalid="${Boolean(errors[f.id])}" aria-describedby="${f.id}-error"><p class="field-error" id="${f.id}-error">${errors[f.id] || ''}</p></div>`).join('')}<p class="help-note">رقم عراقي بصيغة 07 أو مع رمز الدولة +964.</p></form>`;
  if (step === 4) content = `<div class="review-head">${phoneVisual(product,color)}<div><strong dir="ltr">${product.name}</strong><span>اختيارك، بكل تفاصيله.</span></div></div><dl class="review-list">${[['الجهاز',product.name,0],['السعة',capacity,1],['اللون',color.name,2],['الاسم',customer.name,3],['رقم الهاتف',customer.phone,3],['البريد الإلكتروني',customer.email,3]].map(([label,value,target],i)=>`<div><dt>${label}</dt><dd ${i!==3?'dir="ltr"':''}>${escapeHtml(value)}</dd><button class="edit-button" data-edit="${target}" aria-label="تعديل ${label}" ${busy?'disabled':''}>تعديل</button></div>`).join('')}</dl><p class="privacy">سيتم استخدام معلوماتك فقط لغرض متابعة وتأكيد الحجز.<br>حالياً النسخة Demo لا ترسل البيانات فعلياً.</p>`;
  return `<div class="step-heading"><p class="step-count">الخطوة ${step+1} من 5</p><h3 tabindex="-1">${titles[step]}</h3><p>${descriptions[step]}</p></div>${content}<p class="inline-error" id="step-error" role="alert">${errors.selection || errors.submission || ''}</p><div class="wizard-actions">${step>0?`<button class="secondary" data-action="back" ${busy?'disabled':''}>رجوع</button>`:''}<button class="primary" data-action="${step===4?'submit':'next'}" ${busy?'disabled aria-busy="true"':''}>${busy?'<span class="spinner" aria-hidden="true"></span> جاري تأكيد حجزك…':step===4?'تأكيد الحجز المسبق':'التالي <span aria-hidden="true">←</span>'}</button></div>`;
}
export function renderAside(state) {
  const product = products.find(p=>p.id===state.productId);
  const color = colors.find(c=>c.id===state.colorId);
  return `<p class="eyebrow">اختيار يستحق الانتظار</p><h3>جهازك القادم.</h3>${phoneVisual(product || products[1],color,'aside-phone')}<strong class="aside-product" dir="ltr">${product?.name || 'iPhone 18 Pro / Pro Max'}</strong><dl class="aside-details"><div><dt>السعة</dt><dd dir="ltr">${state.capacity || '—'}</dd></div><div><dt>اللون</dt><dd>${color ? `<span class="mini-swatch" style="background:${color.hex}"></span><span lang="en">${color.name}</span>`:'—'}</dd></div></dl><div class="aside-note"><span aria-hidden="true">◇</span><p>من الاختيار إلى التأكيد.<br><small>تجربة بسيطة، مصممة لأجلك.</small></p></div>`;
}
